# Generated by Django 6.0.3 on 2026-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Toyota', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Innova', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(default='Unknown Driver', max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
